"""Initial migration

Revision ID: 17860080be8c
Revises: 
Create Date: 2025-07-09 16:46:24.144282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17860080be8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('resume_name', sa.String(length=255), nullable=True),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
