"""schema check

Revision ID: 3b1d02cfa0a5
Revises: 2b6a78668c7a
Create Date: 2025-08-12 12:25:46.498369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1d02cfa0a5'
down_revision = '2b6a78668c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('password_reset_requests', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_prr_email'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_prr_status'), table_name='password_reset_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prr_status'), 'password_reset_requests', ['status'], unique=False)
    op.create_index(op.f('ix_prr_email'), 'password_reset_requests', ['email'], unique=False)
    op.alter_column('password_reset_requests', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_table('notifications')
    # ### end Alembic commands ###
