"""Add resume edit permission fields

Revision ID: abbbb5e9609a
Revises: 95bb77714330
Create Date: 2025-09-15 09:38:28.353138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbbb5e9609a'
down_revision = '95bb77714330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_edit_permission', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('resume_edit_granted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'resume_edit_granted_at')
    op.drop_column('applications', 'resume_edit_permission')
    # ### end Alembic commands ###
