"""Remove resume edit permission fields

Revision ID: c8c8e8f8d9e1
Revises: abbbb5e9609a
Create Date: 2025-09-15 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c8e8f8d9e1'
down_revision = 'abbbb5e9609a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'resume_edit_granted_at')
    op.drop_column('applications', 'resume_edit_permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_edit_permission', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('resume_edit_granted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###